Fix running the test suite
The rspec-collection_matchers documentation advise to require
rspec-collection_matchers form `spec_helper.rb`.

This fix:

```
Failure/Error: expect(problems).to have(1).problems

NoMethodError:
  undefined method `have' for #<RSpec::ExampleGroups::CheckUnsafeInterpolations::WithFixDisabled::ExecWithUnsafeInterpolationInCommand "detects an unsafe exec command argument" (./spec/puppet-lint/plugins/check_unsafe_interpolations_spec.rb:20)>
```